# Use postgres/example user/password credentials
version: "3"
services:
  server:
    build: ./server
    image: noshuas/hackreactor:server
    ports:
      - 5000:5000
  database:
    build: ./database
    image: noshuas/hackreactor:database
  loadBalancer:
    build: ./loadBalancer
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

    sysctls:
      net.ipv4.ip_local_port_range: 12000 65535
    image: noshuas/hackreactor:loadBalancer
