FROM envoyproxy/envoy-dev:f2906f5ce372814b8e6f688a0e1766703d8b56f2
COPY envoy.yaml /etc/envoy/envoy.yaml
RUN echo 'net.ipv4.ip_local_port_range = 12000 65535' >> /etc/sysctl.conf
RUN echo 'fs.file-max = 1048576' >> /etc/sysctl.conf
RUN echo '*                soft    nofile          1048576' >> /etc/security/limits.conf
RUN echo '*                hard    nofile          1048576' >> /etc/security/limits.conf
RUN echo 'root             soft    nofile          1048576' >> /etc/security/limits.conf
RUN echo 'root             hard    nofile          1048576' >> /etc/security/limits.conf
RUN chmod go+r /etc/envoy/envoy.yaml